#!/bin/sh -l
# The default values for p_prob is 0.05.
# To run this: qsub -v prob=probability path-omp_weak-.pbs

s_sub=${sub:-5}

rm weak_omp_main*

m_main=(100 200 400 800 1200 1600 2000 2400)
cont=0

for n_threads in 1 2 4 8 12 16 20 24
do

	module load cs5220
	cd $PBS_O_WORKDIR

	#PBS -l nodes=1:ppn=24
	#PBS -l walltime=0:30:00
	#PBS -N path
	#PBS -j oe

	export OMP_NUM_THREADS=${n_threads}
	./interpolate ${m_main[cont]} ${s_sub} >> weak_omp_${m_main}.txt
	
	let cont=$cont+1
done
