#!/bin/sh -l
# The default values for n_nodes and p_prob are 2000 and 0.05 respectively.
# To run this: qsub -v nodes=number_of_nodes,prob=probability path.pbs

dim=${size:-100}

rm strong_omp_${dim}*

for dim in 100 200 300 500 800 1000 1500 2000 2500
do

	module load cs5220
	cd $PBS_O_WORKDIR

	#PBS -l nodes=1:ppn=24
	#PBS -l walltime=0:30:00
	#PBS -N path
	#PBS -j oe

	
	export OMP_NUM_THREADS=${n_threads}
	./interpolate ${dim} 5 >> strong_omp_${p_prob}_${n_nodes}.txt
done
