#!/bin/sh -l
# The default values for n_nodes and p_prob are 2000 and 0.05 respectively.
# To run this: qsub -v nodes=number_of_nodes,prob=probability path.pbs

m_main=${main:-1000}
s_sub=${sub:-10}

rm strong_${m_main}_${s_sub}*

for n_threads in 1 2 3 5 8 10 15 20 24
do

	module load cs5220
	cd $PBS_O_WORKDIR

	#PBS -l nodes=1:ppn=24
	#PBS -l walltime=0:30:00
	#PBS -N path
	#PBS -j oe

	
	export OMP_NUM_THREADS=${n_threads}
	./interpolate 1000 10 >> strong_${n_threads}.txt
done
